# Generated by Django 5.1.2 on 2024-10-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nro_reparto', models.IntegerField()),
                ('chofer', models.CharField(max_length=100)),
                ('acompanante', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(max_length=100)),
                ('facturas', models.IntegerField()),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado'), ('Finalizado', 'Finalizado')], default='Abierto', max_length=20)),
                ('entregas', models.IntegerField(default=0)),
                ('incompletos', models.IntegerField(default=0)),
            ],
        ),
    ]
