# Generated by Django 5.1.2 on 2024-10-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Balancín', 'Balancín'), ('Semi', 'Semi')], max_length=20)),
                ('hidrogrua', models.BooleanField(default=False)),
                ('carretilla', models.BooleanField(default=False)),
                ('fecha_adquisicion', models.DateField()),
            ],
        ),
    ]
