# Generated by Django 5.1.2 on 2024-10-15 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='fecha_adquisicion',
            new_name='ruta',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vtv',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
    ]
